// Source de vérité serveur pour les paires de champions (voir CONTRACT.md section 6 & 7).
// champA = champion attribué aux civils (la "majorité").
// champB = champion attribué aux undercover (la version "proche" thématiquement).
// Liste fixe, tirée aléatoirement à chaque partie (server/src/content/pairsStore.ts) — pas
// d'édition en cours de partie, chaque room tire indépendamment des autres.
//
// La difficulté n'est pas un champ à part : elle vient de la proximité champA/champB. Le pool
// mélange volontairement des paires très proches (quasi-jumelles thématiques, undercover
// facile à camoufler) et des paires plus lâches (undercover plus repérable), pour que chaque
// tirage varie en difficulté d'une partie à l'autre.

import type { ChampionPair } from '../types.js';

export const championPairs: ChampionPair[] = [
  {
    id: 'garen-darius',
    champA: 'Garen',
    champB: 'Darius',
    theme: "Lames rivales Demacia/Noxus",
    lanes: ['Top'],
  },
  {
    id: 'ashe-sivir',
    champA: 'Ashe',
    champB: 'Sivir',
    theme: 'Tireuses hypercarry classiques',
    lanes: ['ADC'],
  },
  {
    id: 'katarina-talon',
    champA: 'Katarina',
    champB: 'Talon',
    theme: "Duo d'assassins mêlée noxiens",
    lanes: ['Mid'],
  },
  {
    id: 'lux-morgana',
    champA: 'Lux',
    champB: 'Morgana',
    theme: 'Sœurs lumière et ténèbres',
    lanes: ['Mid', 'Support'],
  },
  {
    id: 'malphite-ornn',
    champA: 'Malphite',
    champB: 'Ornn',
    theme: 'Colosses de pierre increvables',
    lanes: ['Top'],
  },
  {
    id: 'caitlyn-missfortune',
    champA: 'Caitlyn',
    champB: 'Miss Fortune',
    theme: "Tireuses armées à l'autorité",
    lanes: ['ADC'],
  },
  {
    id: 'jinx-vayne',
    champA: 'Jinx',
    champB: 'Vayne',
    theme: 'Justicières explosives à distance',
    lanes: ['ADC'],
  },
  {
    id: 'yasuo-yone',
    champA: 'Yasuo',
    champB: 'Yone',
    theme: 'Frères liés par la lame et le vent',
    lanes: ['Mid', 'Top'],
  },
  {
    id: 'vi-jax',
    champA: 'Vi',
    champB: 'Jax',
    theme: 'Brutes au poing redoutable',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'nidalee-rengar',
    champA: 'Nidalee',
    champB: 'Rengar',
    theme: 'Chasseuse et prédateur rivaux',
    lanes: ['Jungle'],
  },
  {
    id: 'xinzhao-renekton',
    champA: 'Xin Zhao',
    champB: 'Renekton',
    theme: 'Guerriers féroces lance et lames',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'ezreal-kaisa',
    champA: 'Ezreal',
    champB: "Kai'Sa",
    theme: 'Explorateurs mobiles, couple canon',
    lanes: ['ADC'],
  },
  {
    id: 'annie-zoe',
    champA: 'Annie',
    champB: 'Zoe',
    theme: "Mages à l'allure enfantine",
    lanes: ['Mid'],
  },
  {
    id: 'braum-thresh',
    champA: 'Braum',
    champB: 'Thresh',
    theme: 'Supports emblématiques à chaîne/bouclier',
    lanes: ['Support'],
  },
  {
    id: 'soraka-janna',
    champA: 'Soraka',
    champB: 'Janna',
    theme: 'Enchanteresses soigneuses protectrices',
    lanes: ['Support'],
  },
  {
    id: 'shen-zed',
    champA: 'Shen',
    champB: 'Zed',
    theme: "Ninjas rivaux d'Ionia, ordre contre ombre",
    lanes: ['Top', 'Mid'],
  },
  {
    id: 'fiora-riven',
    champA: 'Fiora',
    champB: 'Riven',
    theme: "Duellistes exilées à l'épée",
    lanes: ['Top'],
  },
  {
    id: 'karma-sona',
    champA: 'Karma',
    champB: 'Sona',
    theme: "Mages spirituelles d'Ionia",
    lanes: ['Support'],
  },
  {
    id: 'teemo-heimerdinger',
    champA: 'Teemo',
    champB: 'Heimerdinger',
    theme: 'Yordles bricoleurs à pièges',
    lanes: ['Top'],
  },
  {
    id: 'nautilus-illaoi',
    champA: 'Nautilus',
    champB: 'Illaoi',
    theme: 'Colosses des profondeurs de Bilgewater',
    lanes: ['Support', 'Top'],
  },
  {
    id: 'kled-rumble',
    champA: 'Kled',
    champB: 'Rumble',
    theme: 'Petits gabarits en engins déchaînés',
    lanes: ['Top'],
  },
  {
    id: 'ahri-neeko',
    champA: 'Ahri',
    champB: 'Neeko',
    theme: 'Métamorphes charmeuses envoûtantes',
    lanes: ['Mid'],
  },
  {
    id: 'diana-leona',
    champA: 'Diana',
    champB: 'Leona',
    theme: 'Rivales de la lune et du soleil',
    lanes: ['Jungle', 'Support'],
  },
  {
    id: 'tristana-corki',
    champA: 'Tristana',
    champB: 'Corki',
    theme: 'Artilleurs miniatures explosifs',
    lanes: ['ADC', 'Mid'],
  },
  {
    id: 'sett-sion',
    champA: 'Sett',
    champB: 'Sion',
    theme: 'Tanks bruisers indestructibles',
    lanes: ['Top'],
  },
  {
    id: 'akali-kayn',
    champA: 'Akali',
    champB: 'Kayn',
    theme: "Assassins mêlée tapis dans l'ombre",
    lanes: ['Mid', 'Jungle'],
  },
  {
    id: 'jhin-varus',
    champA: 'Jhin',
    champB: 'Varus',
    theme: 'Tireurs maudits aux mises en scène macabres',
    lanes: ['ADC'],
  },
  {
    id: 'yuumi-seraphine',
    champA: 'Yuumi',
    champB: 'Seraphine',
    theme: 'Supports pop stars musiciennes',
    lanes: ['Support'],
  },
  {
    id: 'pyke-senna',
    champA: 'Pyke',
    champB: 'Senna',
    theme: 'Bourreaux vengeurs liés à Thresh',
    lanes: ['Support', 'ADC'],
  },
  {
    id: 'camille-irelia',
    champA: 'Camille',
    champB: 'Irelia',
    theme: 'Lames disciplinées très mobiles',
    lanes: ['Top'],
  },
  {
    id: 'warwick-volibear',
    champA: 'Warwick',
    champB: 'Volibear',
    theme: 'Bêtes féroces de la jungle, loup contre ours',
    lanes: ['Jungle'],
  },
  {
    id: 'blitzcrank-alistar',
    champA: 'Blitzcrank',
    champB: 'Alistar',
    theme: 'Supports increvables à engage explosif',
    lanes: ['Support'],
  },
  {
    id: 'lulu-nami',
    champA: 'Lulu',
    champB: 'Nami',
    theme: 'Enchanteresses fantaisistes protectrices',
    lanes: ['Support'],
  },
  {
    id: 'twistedfate-graves',
    champA: 'Twisted Fate',
    champB: 'Graves',
    theme: 'Rivaux de Bilgewater, cartes contre flingue',
    lanes: ['Mid', 'ADC'],
  },
  {
    id: 'draven-lucian',
    champA: 'Draven',
    champB: 'Lucian',
    theme: 'Carries tape-à-l’œil, showmen de la bot lane',
    lanes: ['ADC'],
  },
  {
    id: 'ekko-leblanc',
    champA: 'Ekko',
    champB: 'LeBlanc',
    theme: 'Manipulateurs du temps et de l’illusion',
    lanes: ['Mid'],
  },
  {
    id: 'elise-evelynn',
    champA: 'Elise',
    champB: 'Evelynn',
    theme: 'Séductrices dissimulant une véritable forme monstrueuse',
    lanes: ['Jungle'],
  },
  {
    id: 'sylas-aatrox',
    champA: 'Sylas',
    champB: 'Aatrox',
    theme: 'Prisonniers devenus armes vivantes',
    lanes: ['Mid', 'Top'],
  },
  {
    id: 'rakan-xayah',
    champA: 'Rakan',
    champB: 'Xayah',
    theme: 'Couple de danseurs emplumés vastaya',
    lanes: ['Support', 'ADC'],
  },
  {
    id: 'aphelios-samira',
    champA: 'Aphelios',
    champB: 'Samira',
    theme: 'Tireurs flamboyants aux armes multiples',
    lanes: ['ADC'],
  },
  {
    id: 'masteryi-tryndamere',
    champA: 'Master Yi',
    champB: 'Tryndamere',
    theme: 'Épéistes solo-carry increvables en fin de partie',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'leesin-khazix',
    champA: 'Lee Sin',
    champB: "Kha'Zix",
    theme: 'Prédateurs mobiles insaisissables de la jungle',
    lanes: ['Jungle'],
  },
  {
    id: 'veigar-ziggs',
    champA: 'Veigar',
    champB: 'Ziggs',
    theme: 'Petits mages à la puissance dévastatrice',
    lanes: ['Mid'],
  },
  {
    id: 'poppy-gnar',
    champA: 'Poppy',
    champB: 'Gnar',
    theme: 'Petits gabarits, marteau et boomerang redoutables',
    lanes: ['Top'],
  },
  {
    id: 'kassadin-malzahar',
    champA: 'Kassadin',
    champB: 'Malzahar',
    theme: 'Mages liés au Néant',
    lanes: ['Mid'],
  },
  // --- Paires très proches (undercover difficile à repérer) ---
  {
    id: 'nasus-renekton',
    champA: 'Nasus',
    champB: 'Renekton',
    theme: 'Frères Ascendus égyptiens, même culte déchu',
    lanes: ['Top'],
  },
  {
    id: 'karthus-mordekaiser',
    champA: 'Karthus',
    champB: 'Mordekaiser',
    theme: 'Seigneurs blindés de la mort et du Néant',
    lanes: ['Mid', 'Jungle'],
  },
  {
    id: 'xerath-velkoz',
    champA: 'Xerath',
    champB: "Vel'Koz",
    theme: 'Artilleurs à distance, énergie pure dévastatrice',
    lanes: ['Mid', 'Support'],
  },
  {
    id: 'anivia-lissandra',
    champA: 'Anivia',
    champB: 'Lissandra',
    theme: 'Maîtresses de la glace du Freljord',
    lanes: ['Mid'],
  },
  // --- Paires plus éloignées (undercover plus facile à repérer) ---
  {
    id: 'amumu-zac',
    champA: 'Amumu',
    champB: 'Zac',
    theme: 'Tanks jungle increvables, momie triste contre gelée',
    lanes: ['Jungle'],
  },
  {
    id: 'singed-drmundo',
    champA: 'Singed',
    champB: 'Dr. Mundo',
    theme: "Chimistes fous de Zaun, styles de combat opposés",
    lanes: ['Top'],
  },
  {
    id: 'taric-galio',
    champA: 'Taric',
    champB: 'Galio',
    theme: 'Gardiens protecteurs, gemme contre gargouille',
    lanes: ['Support', 'Mid'],
  },
];
