// Source de vérité serveur pour les paires de champions (voir CONTRACT.md section 6 & 7).
// champA = champion attribué aux civils (la "majorité").
// champB = champion attribué aux undercover (la version "proche" thématiquement).
// Liste fixe, tirée aléatoirement à chaque partie (server/src/content/pairsStore.ts) — pas
// d'édition en cours de partie, chaque room tire indépendamment des autres.
//
// La difficulté n'est pas un champ à part : elle vient de la proximité champA/champB. Le pool
// mélange volontairement des paires très proches (quasi-jumelles thématiques, undercover
// facile à camoufler) et des paires plus lâches (undercover plus repérable), pour que chaque
// tirage varie en difficulté d'une partie à l'autre.

import type { ChampionPair } from '../types.js';

export const championPairs: ChampionPair[] = [
  {
    id: 'garen-darius',
    champA: 'Garen',
    champB: 'Darius',
    theme: "Lames rivales Demacia/Noxus",
    lanes: ['Top'],
  },
  {
    id: 'ashe-sivir',
    champA: 'Ashe',
    champB: 'Sivir',
    theme: 'Tireuses hypercarry classiques',
    lanes: ['ADC'],
  },
  {
    id: 'katarina-talon',
    champA: 'Katarina',
    champB: 'Talon',
    theme: "Duo d'assassins mêlée noxiens",
    lanes: ['Mid'],
  },
  {
    id: 'lux-morgana',
    champA: 'Lux',
    champB: 'Morgana',
    theme: 'Sœurs lumière et ténèbres',
    lanes: ['Mid', 'Support'],
  },
  {
    id: 'malphite-ornn',
    champA: 'Malphite',
    champB: 'Ornn',
    theme: 'Colosses de pierre increvables',
    lanes: ['Top'],
  },
  {
    id: 'caitlyn-missfortune',
    champA: 'Caitlyn',
    champB: 'Miss Fortune',
    theme: "Tireuses armées à l'autorité",
    lanes: ['ADC'],
  },
  {
    id: 'jinx-vayne',
    champA: 'Jinx',
    champB: 'Vayne',
    theme: 'Justicières explosives à distance',
    lanes: ['ADC'],
  },
  {
    id: 'yasuo-yone',
    champA: 'Yasuo',
    champB: 'Yone',
    theme: 'Frères liés par la lame et le vent',
    lanes: ['Mid', 'Top'],
  },
  {
    id: 'vi-jax',
    champA: 'Vi',
    champB: 'Jax',
    theme: 'Brutes au poing redoutable',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'nidalee-rengar',
    champA: 'Nidalee',
    champB: 'Rengar',
    theme: 'Chasseuse et prédateur rivaux',
    lanes: ['Jungle'],
  },
  {
    id: 'xinzhao-renekton',
    champA: 'Xin Zhao',
    champB: 'Renekton',
    theme: 'Guerriers féroces lance et lames',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'ezreal-kaisa',
    champA: 'Ezreal',
    champB: "Kai'Sa",
    theme: 'Explorateurs mobiles, couple canon',
    lanes: ['ADC'],
  },
  {
    id: 'annie-zoe',
    champA: 'Annie',
    champB: 'Zoe',
    theme: "Mages à l'allure enfantine",
    lanes: ['Mid'],
  },
  {
    id: 'braum-thresh',
    champA: 'Braum',
    champB: 'Thresh',
    theme: 'Supports emblématiques à chaîne/bouclier',
    lanes: ['Support'],
  },
  {
    id: 'soraka-janna',
    champA: 'Soraka',
    champB: 'Janna',
    theme: 'Enchanteresses soigneuses protectrices',
    lanes: ['Support'],
  },
  {
    id: 'shen-zed',
    champA: 'Shen',
    champB: 'Zed',
    theme: "Ninjas rivaux d'Ionia, ordre contre ombre",
    lanes: ['Top', 'Mid'],
  },
  {
    id: 'fiora-riven',
    champA: 'Fiora',
    champB: 'Riven',
    theme: "Duellistes exilées à l'épée",
    lanes: ['Top'],
  },
  {
    id: 'karma-sona',
    champA: 'Karma',
    champB: 'Sona',
    theme: "Mages spirituelles d'Ionia",
    lanes: ['Support'],
  },
  {
    id: 'teemo-heimerdinger',
    champA: 'Teemo',
    champB: 'Heimerdinger',
    theme: 'Yordles bricoleurs à pièges',
    lanes: ['Top'],
  },
  {
    id: 'nautilus-illaoi',
    champA: 'Nautilus',
    champB: 'Illaoi',
    theme: 'Colosses des profondeurs de Bilgewater',
    lanes: ['Support', 'Top'],
  },
  {
    id: 'kled-rumble',
    champA: 'Kled',
    champB: 'Rumble',
    theme: 'Petits gabarits en engins déchaînés',
    lanes: ['Top'],
  },
  {
    id: 'ahri-neeko',
    champA: 'Ahri',
    champB: 'Neeko',
    theme: 'Métamorphes charmeuses envoûtantes',
    lanes: ['Mid'],
  },
  {
    id: 'diana-leona',
    champA: 'Diana',
    champB: 'Leona',
    theme: 'Rivales de la lune et du soleil',
    lanes: ['Jungle', 'Support'],
  },
  {
    id: 'tristana-corki',
    champA: 'Tristana',
    champB: 'Corki',
    theme: 'Artilleurs miniatures explosifs',
    lanes: ['ADC', 'Mid'],
  },
  {
    id: 'sett-sion',
    champA: 'Sett',
    champB: 'Sion',
    theme: 'Tanks bruisers indestructibles',
    lanes: ['Top'],
  },
  {
    id: 'akali-kayn',
    champA: 'Akali',
    champB: 'Kayn',
    theme: "Assassins mêlée tapis dans l'ombre",
    lanes: ['Mid', 'Jungle'],
  },
  {
    id: 'jhin-varus',
    champA: 'Jhin',
    champB: 'Varus',
    theme: 'Tireurs maudits aux mises en scène macabres',
    lanes: ['ADC'],
  },
  {
    id: 'yuumi-seraphine',
    champA: 'Yuumi',
    champB: 'Seraphine',
    theme: 'Supports pop stars musiciennes',
    lanes: ['Support'],
  },
  {
    id: 'pyke-senna',
    champA: 'Pyke',
    champB: 'Senna',
    theme: 'Bourreaux vengeurs liés à Thresh',
    lanes: ['Support', 'ADC'],
  },
  {
    id: 'camille-irelia',
    champA: 'Camille',
    champB: 'Irelia',
    theme: 'Lames disciplinées très mobiles',
    lanes: ['Top'],
  },
  {
    id: 'warwick-volibear',
    champA: 'Warwick',
    champB: 'Volibear',
    theme: 'Bêtes féroces de la jungle, loup contre ours',
    lanes: ['Jungle'],
  },
  {
    id: 'blitzcrank-alistar',
    champA: 'Blitzcrank',
    champB: 'Alistar',
    theme: 'Supports increvables à engage explosif',
    lanes: ['Support'],
  },
  {
    id: 'lulu-nami',
    champA: 'Lulu',
    champB: 'Nami',
    theme: 'Enchanteresses fantaisistes protectrices',
    lanes: ['Support'],
  },
  {
    id: 'twistedfate-graves',
    champA: 'Twisted Fate',
    champB: 'Graves',
    theme: 'Rivaux de Bilgewater, cartes contre flingue',
    lanes: ['Mid', 'ADC'],
  },
  {
    id: 'draven-lucian',
    champA: 'Draven',
    champB: 'Lucian',
    theme: 'Carries tape-à-l’œil, showmen de la bot lane',
    lanes: ['ADC'],
  },
  {
    id: 'ekko-leblanc',
    champA: 'Ekko',
    champB: 'LeBlanc',
    theme: 'Manipulateurs du temps et de l’illusion',
    lanes: ['Mid'],
  },
  {
    id: 'elise-evelynn',
    champA: 'Elise',
    champB: 'Evelynn',
    theme: 'Séductrices dissimulant une véritable forme monstrueuse',
    lanes: ['Jungle'],
  },
  {
    id: 'sylas-aatrox',
    champA: 'Sylas',
    champB: 'Aatrox',
    theme: 'Prisonniers devenus armes vivantes',
    lanes: ['Mid', 'Top'],
  },
  {
    id: 'rakan-xayah',
    champA: 'Rakan',
    champB: 'Xayah',
    theme: 'Couple de danseurs emplumés vastaya',
    lanes: ['Support', 'ADC'],
  },
  {
    id: 'aphelios-samira',
    champA: 'Aphelios',
    champB: 'Samira',
    theme: 'Tireurs flamboyants aux armes multiples',
    lanes: ['ADC'],
  },
  {
    id: 'masteryi-tryndamere',
    champA: 'Master Yi',
    champB: 'Tryndamere',
    theme: 'Épéistes solo-carry increvables en fin de partie',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'leesin-khazix',
    champA: 'Lee Sin',
    champB: "Kha'Zix",
    theme: 'Prédateurs mobiles insaisissables de la jungle',
    lanes: ['Jungle'],
  },
  {
    id: 'veigar-ziggs',
    champA: 'Veigar',
    champB: 'Ziggs',
    theme: 'Petits mages à la puissance dévastatrice',
    lanes: ['Mid'],
  },
  {
    id: 'poppy-gnar',
    champA: 'Poppy',
    champB: 'Gnar',
    theme: 'Petits gabarits, marteau et boomerang redoutables',
    lanes: ['Top'],
  },
  {
    id: 'kassadin-malzahar',
    champA: 'Kassadin',
    champB: 'Malzahar',
    theme: 'Mages liés au Néant',
    lanes: ['Mid'],
  },
  // --- Paires très proches (undercover difficile à repérer) ---
  {
    id: 'nasus-renekton',
    champA: 'Nasus',
    champB: 'Renekton',
    theme: 'Frères Ascendus égyptiens, même culte déchu',
    lanes: ['Top'],
  },
  {
    id: 'karthus-mordekaiser',
    champA: 'Karthus',
    champB: 'Mordekaiser',
    theme: 'Seigneurs blindés de la mort et du Néant',
    lanes: ['Mid', 'Jungle'],
  },
  {
    id: 'xerath-velkoz',
    champA: 'Xerath',
    champB: "Vel'Koz",
    theme: 'Artilleurs à distance, énergie pure dévastatrice',
    lanes: ['Mid', 'Support'],
  },
  {
    id: 'anivia-lissandra',
    champA: 'Anivia',
    champB: 'Lissandra',
    theme: 'Maîtresses de la glace du Freljord',
    lanes: ['Mid'],
  },
  // --- Paires plus éloignées (undercover plus facile à repérer) ---
  {
    id: 'amumu-zac',
    champA: 'Amumu',
    champB: 'Zac',
    theme: 'Tanks jungle increvables, momie triste contre gelée',
    lanes: ['Jungle'],
  },
  {
    id: 'singed-drmundo',
    champA: 'Singed',
    champB: 'Dr. Mundo',
    theme: "Chimistes fous de Zaun, styles de combat opposés",
    lanes: ['Top'],
  },
  {
    id: 'taric-galio',
    champA: 'Taric',
    champB: 'Galio',
    theme: 'Gardiens protecteurs, gemme contre gargouille',
    lanes: ['Support', 'Mid'],
  },
  // --- Nouvelles paires difficiles (undercover très difficile à repérer) ---
  {
    id: 'chogath-kogmaw',
    champA: "Cho'Gath",
    champB: "Kog'Maw",
    theme: 'Monstres du Néant emblématiques, dévoreurs insatiables',
    lanes: ['Top', 'ADC'],
  },
  {
    id: 'rammus-skarner',
    champA: 'Rammus',
    champB: 'Skarner',
    theme: 'Tanks blindés increvables à la carapace redoutable',
    lanes: ['Jungle'],
  },
  {
    id: 'fiddlesticks-shaco',
    champA: 'Fiddlesticks',
    champB: 'Shaco',
    theme: 'Terreurs de la jungle à l\'humour glaçant, maîtres de la peur',
    lanes: ['Jungle'],
  },
  {
    id: 'jayce-urgot',
    champA: 'Jayce',
    champB: 'Urgot',
    theme: 'Rivaux augmentés par la machine, tension Piltover/Zaun',
    lanes: ['Top'],
  },
  {
    id: 'vladimir-swain',
    champA: 'Vladimir',
    champB: 'Swain',
    theme: 'Membres du Haut Commandement noxien, magie du sang',
    lanes: ['Mid'],
  },
  // --- Nouvelles paires moyennes (undercover repérable avec attention) ---
  {
    id: 'qiyana-taliyah',
    champA: 'Qiyana',
    champB: 'Taliyah',
    theme: 'Jeunes prodiges élémentaires, maîtresses du terrain rocheux',
    lanes: ['Mid'],
  },
  {
    id: 'trundle-sejuani',
    champA: 'Trundle',
    champB: 'Sejuani',
    theme: 'Seigneurs de guerre bruts du Freljord',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'kindred-zilean',
    champA: 'Kindred',
    champB: 'Zilean',
    theme: 'Figures liées à la mort et au temps, gardiens du destin des âmes',
    lanes: ['Jungle', 'Support'],
  },
  {
    id: 'gragas-olaf',
    champA: 'Gragas',
    champB: 'Olaf',
    theme: 'Guerriers indisciplinés du Freljord, force brute sans limites',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'bard-ivern',
    champA: 'Bard',
    champB: 'Ivern',
    theme: 'Errants excentriques et bienveillants, hors des conventions',
    lanes: ['Support', 'Jungle'],
  },
  // --- Encore plus de paires difficiles (undercover très difficile à repérer) ---
  {
    id: 'aurelionsol-shyvana',
    champA: 'Aurelion Sol',
    champB: 'Shyvana',
    theme: 'Dragons de Runeterra, céleste contre sang-mêlé',
    lanes: ['Mid', 'Jungle'],
  },
  {
    id: 'azir-xerath',
    champA: 'Azir',
    champB: 'Xerath',
    theme: 'Anciens souverains/mages shurimans ramenés par la magie',
    lanes: ['Mid'],
  },
  {
    id: 'brand-cassiopeia',
    champA: 'Brand',
    champB: 'Cassiopeia',
    theme: "Victimes de malédictions les ayant transformées en monstres",
    lanes: ['Mid'],
  },
  {
    id: 'kalista-thresh',
    champA: 'Kalista',
    champB: 'Thresh',
    theme: "Esprit vengeur et son bourreau, liés pour l'éternité par la trahison",
    lanes: ['ADC', 'Support'],
  },
  {
    id: 'kennen-zed',
    champA: 'Kennen',
    champB: 'Zed',
    theme: "Ninjas rapides d'Ionia maniant des pouvoirs surnaturels",
    lanes: ['Top', 'Mid'],
  },
  {
    id: 'nocturne-warwick',
    champA: 'Nocturne',
    champB: 'Warwick',
    theme: 'Cauchemars de la jungle se nourrissant de peur et de sang',
    lanes: ['Jungle'],
  },
  {
    id: 'orianna-viktor',
    champA: 'Orianna',
    champB: 'Viktor',
    theme: 'Êtres mêlant chair et mécanique de Piltover-Zaun',
    lanes: ['Mid'],
  },
  {
    id: 'kayle-morgana',
    champA: 'Kayle',
    champB: 'Morgana',
    theme: "Sœurs déchues, l'une angélique, l'autre vengeresse",
    lanes: ['Top', 'Support'],
  },
  {
    id: 'jarvaniv-pantheon',
    champA: 'Jarvan IV',
    champB: 'Pantheon',
    theme: 'Guerriers disciplinés à la lance, meneurs infaillibles au combat',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'udyr-ornn',
    champA: 'Udyr',
    champB: 'Ornn',
    theme: 'Divinités et esprits ancestraux du Freljord',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'yorick-karthus',
    champA: 'Yorick',
    champB: 'Karthus',
    theme: 'Figures macabres maîtrisant la mort et les morts-vivants',
    lanes: ['Top', 'Mid'],
  },
  // --- Encore plus de paires moyennes (undercover repérable avec attention) ---
  {
    id: 'fizz-gangplank',
    champA: 'Fizz',
    champB: 'Gangplank',
    theme: 'Figures espiègles et redoutables des mers de Bilgewater',
    lanes: ['Mid', 'Top'],
  },
  {
    id: 'hecarim-nunu',
    champA: 'Hecarim',
    champB: 'Nunu & Willump',
    theme: 'Duos cavalier/monture emblématiques, spectral contre neige',
    lanes: ['Jungle'],
  },
  {
    id: 'lillia-ivern',
    champA: 'Lillia',
    champB: 'Ivern',
    theme: 'Esprits doux protecteurs de la forêt, à l\'opposé des junglers brutaux',
    lanes: ['Jungle'],
  },
  {
    id: 'maokai-zyra',
    champA: 'Maokai',
    champB: 'Zyra',
    theme: 'Manifestations végétales vengeresses de la nature',
    lanes: ['Support', 'Jungle'],
  },
  {
    id: 'wukong-xinzhao',
    champA: 'Wukong',
    champB: 'Xin Zhao',
    theme: 'Guerriers agiles à l\'arme de mêlée, showmen du combat',
    lanes: ['Jungle', 'Top'],
  },
  {
    id: 'quinn-vayne',
    champA: 'Quinn',
    champB: 'Vayne',
    theme: 'Justiciers solitaires traquant leurs cibles sans relâche',
    lanes: ['Top', 'ADC'],
  },
  {
    id: 'reksai-skarner',
    champA: "Rek'Sai",
    champB: 'Skarner',
    theme: 'Prédateurs souterrains émergeant brusquement du sol',
    lanes: ['Jungle'],
  },
  {
    id: 'ryze-kassadin',
    champA: 'Ryze',
    champB: 'Kassadin',
    theme: 'Mages vétérans protégeant Runeterra de menaces cosmiques',
    lanes: ['Mid'],
  },
  {
    id: 'tahmkench-illaoi',
    champA: 'Tahm Kench',
    champB: 'Illaoi',
    theme: 'Figures monstrueuses et imposantes liées aux eaux et à la foi de Bilgewater',
    lanes: ['Support', 'Top'],
  },
  {
    id: 'twitch-singed',
    champA: 'Twitch',
    champB: 'Singed',
    theme: 'Figures toxiques de Zaun, rat des égouts contre chimiste fou',
    lanes: ['ADC', 'Top'],
  },
  {
    id: 'syndra-zoe',
    champA: 'Syndra',
    champB: 'Zoe',
    theme: 'Prodiges de la magie à l\'apparence trompeusement juvénile',
    lanes: ['Mid'],
  },
];
