// Source de vérité serveur pour les paires de champions (voir CONTRACT.md section 6 & 7).
// champA = champion attribué aux civils (la "majorité").
// champB = champion attribué aux undercover (la version "proche" thématiquement).
// Toutes les entrées ci-dessous sont la liste de base fournie par défaut : enabled = true,
// isCustom = false. Les ajouts faits par un host en cours de partie (pairs:add) viendront
// s'ajouter à ce tableau en mémoire côté serveur avec isCustom = true.

export interface ChampionPair {
  id: string;
  champA: string;
  champB: string;
  theme: string; // ex: "Tanks brutaux", "Duo assassins mêlée"
  lanes?: string[]; // ex: ["Top"], optionnel
  enabled: boolean;
  isCustom: boolean;
}

export const championPairs: ChampionPair[] = [
  {
    id: 'garen-darius',
    champA: 'Garen',
    champB: 'Darius',
    theme: "Lames rivales Demacia/Noxus",
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'ashe-sivir',
    champA: 'Ashe',
    champB: 'Sivir',
    theme: 'Tireuses hypercarry classiques',
    lanes: ['ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'katarina-talon',
    champA: 'Katarina',
    champB: 'Talon',
    theme: "Duo d'assassins mêlée noxiens",
    lanes: ['Mid'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'lux-morgana',
    champA: 'Lux',
    champB: 'Morgana',
    theme: 'Sœurs lumière et ténèbres',
    lanes: ['Mid', 'Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'malphite-ornn',
    champA: 'Malphite',
    champB: 'Ornn',
    theme: 'Colosses de pierre increvables',
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'caitlyn-missfortune',
    champA: 'Caitlyn',
    champB: 'Miss Fortune',
    theme: "Tireuses armées à l'autorité",
    lanes: ['ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'jinx-vayne',
    champA: 'Jinx',
    champB: 'Vayne',
    theme: 'Justicières explosives à distance',
    lanes: ['ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'yasuo-yone',
    champA: 'Yasuo',
    champB: 'Yone',
    theme: 'Frères liés par la lame et le vent',
    lanes: ['Mid', 'Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'vi-jax',
    champA: 'Vi',
    champB: 'Jax',
    theme: 'Brutes au poing redoutable',
    lanes: ['Jungle', 'Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'nidalee-rengar',
    champA: 'Nidalee',
    champB: 'Rengar',
    theme: 'Chasseuse et prédateur rivaux',
    lanes: ['Jungle'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'xinzhao-renekton',
    champA: 'Xin Zhao',
    champB: 'Renekton',
    theme: 'Guerriers féroces lance et lames',
    lanes: ['Jungle', 'Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'ezreal-kaisa',
    champA: 'Ezreal',
    champB: "Kai'Sa",
    theme: 'Explorateurs mobiles, couple canon',
    lanes: ['ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'annie-zoe',
    champA: 'Annie',
    champB: 'Zoe',
    theme: "Mages à l'allure enfantine",
    lanes: ['Mid'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'braum-thresh',
    champA: 'Braum',
    champB: 'Thresh',
    theme: 'Supports emblématiques à chaîne/bouclier',
    lanes: ['Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'soraka-janna',
    champA: 'Soraka',
    champB: 'Janna',
    theme: 'Enchanteresses soigneuses protectrices',
    lanes: ['Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'shen-zed',
    champA: 'Shen',
    champB: 'Zed',
    theme: "Ninjas rivaux d'Ionia, ordre contre ombre",
    lanes: ['Top', 'Mid'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'fiora-riven',
    champA: 'Fiora',
    champB: 'Riven',
    theme: "Duellistes exilées à l'épée",
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'karma-sona',
    champA: 'Karma',
    champB: 'Sona',
    theme: "Mages spirituelles d'Ionia",
    lanes: ['Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'teemo-heimerdinger',
    champA: 'Teemo',
    champB: 'Heimerdinger',
    theme: 'Yordles bricoleurs à pièges',
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'nautilus-illaoi',
    champA: 'Nautilus',
    champB: 'Illaoi',
    theme: 'Colosses des profondeurs de Bilgewater',
    lanes: ['Support', 'Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'kled-rumble',
    champA: 'Kled',
    champB: 'Rumble',
    theme: 'Petits gabarits en engins déchaînés',
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'ahri-neeko',
    champA: 'Ahri',
    champB: 'Neeko',
    theme: 'Métamorphes charmeuses envoûtantes',
    lanes: ['Mid'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'diana-leona',
    champA: 'Diana',
    champB: 'Leona',
    theme: 'Rivales de la lune et du soleil',
    lanes: ['Jungle', 'Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'tristana-corki',
    champA: 'Tristana',
    champB: 'Corki',
    theme: 'Artilleurs miniatures explosifs',
    lanes: ['ADC', 'Mid'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'sett-sion',
    champA: 'Sett',
    champB: 'Sion',
    theme: 'Tanks bruisers indestructibles',
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'akali-kayn',
    champA: 'Akali',
    champB: 'Kayn',
    theme: "Assassins mêlée tapis dans l'ombre",
    lanes: ['Mid', 'Jungle'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'jhin-varus',
    champA: 'Jhin',
    champB: 'Varus',
    theme: 'Tireurs maudits aux mises en scène macabres',
    lanes: ['ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'yuumi-seraphine',
    champA: 'Yuumi',
    champB: 'Seraphine',
    theme: 'Supports pop stars musiciennes',
    lanes: ['Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'pyke-senna',
    champA: 'Pyke',
    champB: 'Senna',
    theme: 'Bourreaux vengeurs liés à Thresh',
    lanes: ['Support', 'ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'camille-irelia',
    champA: 'Camille',
    champB: 'Irelia',
    theme: 'Lames disciplinées très mobiles',
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'warwick-volibear',
    champA: 'Warwick',
    champB: 'Volibear',
    theme: 'Bêtes féroces de la jungle, loup contre ours',
    lanes: ['Jungle'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'blitzcrank-alistar',
    champA: 'Blitzcrank',
    champB: 'Alistar',
    theme: 'Supports increvables à engage explosif',
    lanes: ['Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'lulu-nami',
    champA: 'Lulu',
    champB: 'Nami',
    theme: 'Enchanteresses fantaisistes protectrices',
    lanes: ['Support'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'twistedfate-graves',
    champA: 'Twisted Fate',
    champB: 'Graves',
    theme: 'Rivaux de Bilgewater, cartes contre flingue',
    lanes: ['Mid', 'ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'draven-lucian',
    champA: 'Draven',
    champB: 'Lucian',
    theme: 'Carries tape-à-l’œil, showmen de la bot lane',
    lanes: ['ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'ekko-leblanc',
    champA: 'Ekko',
    champB: 'LeBlanc',
    theme: 'Manipulateurs du temps et de l’illusion',
    lanes: ['Mid'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'elise-evelynn',
    champA: 'Elise',
    champB: 'Evelynn',
    theme: 'Séductrices dissimulant une véritable forme monstrueuse',
    lanes: ['Jungle'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'sylas-aatrox',
    champA: 'Sylas',
    champB: 'Aatrox',
    theme: 'Prisonniers devenus armes vivantes',
    lanes: ['Mid', 'Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'rakan-xayah',
    champA: 'Rakan',
    champB: 'Xayah',
    theme: 'Couple de danseurs emplumés vastaya',
    lanes: ['Support', 'ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'aphelios-samira',
    champA: 'Aphelios',
    champB: 'Samira',
    theme: 'Tireurs flamboyants aux armes multiples',
    lanes: ['ADC'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'masteryi-tryndamere',
    champA: 'Master Yi',
    champB: 'Tryndamere',
    theme: 'Épéistes solo-carry increvables en fin de partie',
    lanes: ['Jungle', 'Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'leesin-khazix',
    champA: 'Lee Sin',
    champB: "Kha'Zix",
    theme: 'Prédateurs mobiles insaisissables de la jungle',
    lanes: ['Jungle'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'veigar-ziggs',
    champA: 'Veigar',
    champB: 'Ziggs',
    theme: 'Petits mages à la puissance dévastatrice',
    lanes: ['Mid'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'poppy-gnar',
    champA: 'Poppy',
    champB: 'Gnar',
    theme: 'Petits gabarits, marteau et boomerang redoutables',
    lanes: ['Top'],
    enabled: true,
    isCustom: false,
  },
  {
    id: 'kassadin-malzahar',
    champA: 'Kassadin',
    champB: 'Malzahar',
    theme: 'Mages liés au Néant',
    lanes: ['Mid'],
    enabled: true,
    isCustom: false,
  },
];
