// Source de vérité serveur pour les paires Pokémon (univers 'pokemon', voir docs/CONTRACT.md
// section 6 & 7 et content/pairsStore.ts).
// champA = Pokémon attribué aux civils (la "majorité").
// champB = Pokémon attribué aux undercover (la version "proche" thématiquement).
// Noms en français officiel (jeux/dessin animé), contrairement aux univers lol/smash qui
// gardent des noms anglais — les Pokémon ont une vraie traduction FR largement plus connue
// du public visé. Liste fixe, tirée aléatoirement à chaque partie — pas d'édition en cours
// de partie.
//
// La difficulté n'est pas un champ à part : elle vient de la proximité champA/champB. Ce pool
// est volontairement TRÈS chargé en paires difficiles (formes régionales quasi identiques —
// Alola/Galar/Hisui — et duos légendaires jumeaux), avec moins de paires moyennes et encore
// moins de paires faciles, pour des parties globalement plus corsées.

import type { ChampionPair } from '../types.js';

export const pokemonPairs: ChampionPair[] = [
  // --- Paires très difficiles : formes régionales quasi identiques (undercover très dur à repérer) ---
  { id: 'raichu-raichualola', champA: 'Raichu', champB: "Raichu d'Alola", theme: 'Même évolution électrique, robe et queue différentes selon la région' },
  { id: 'goupix-goupixalola', champA: 'Goupix', champB: "Goupix d'Alola", theme: 'Renard à six queues, feu contre glace' },
  { id: 'sabelette-sabeletealola', champA: 'Sabelette', champB: "Sabelette d'Alola", theme: 'Même tatou des sables, désert contre neige' },
  { id: 'miaouss-miaoussalola', champA: 'Miaouss', champB: "Miaouss d'Alola", theme: 'Même chat à pièce, pelage doré contre crinière blanche' },
  { id: 'miaouss-miaoussgalar', champA: 'Miaouss', champB: 'Miaouss de Galar', theme: 'Même chat à pièce, version rustique galaroise' },
  { id: 'taupiqueur-taupiqueuralola', champA: 'Taupiqueur', champB: "Taupiqueur d'Alola", theme: 'Même taupe souterraine, moustaches dorées contre poils blancs' },
  { id: 'racaillou-racailloualola', champA: 'Racaillou', champB: "Racaillou d'Alola", theme: 'Même roche vivante, magnétisme et fragments de métal' },
  { id: 'tadmorv-tadmorvalola', champA: 'Tadmorv', champB: "Tadmorv d'Alola", theme: 'Même tas de boue toxique, violet contre déchets recyclés' },
  { id: 'ossatueur-ossatueuralola', champA: 'Ossatueur', champB: "Ossatueur d'Alola", theme: 'Même crâne au bras cassant, os contre flammes spectrales' },
  { id: 'noadkoko-noadkokoalola', champA: 'Noadkoko', champB: "Noadkoko d'Alola", theme: 'Même palmier à têtes, trois têtes contre cou interminable' },
  { id: 'ponyta-ponytagalar', champA: 'Ponyta', champB: 'Ponyta de Galar', theme: 'Même poulain de feu, crinière flamboyante contre crinière licorne' },
  { id: 'galopa-galopagalar', champA: 'Galopa', champB: 'Galopa de Galar', theme: 'Même destrier ardent, robe de feu contre robe psychique' },
  { id: 'smogogo-smogogogalar', champA: 'Smogogo', champB: 'Smogogo de Galar', theme: 'Même duo de gaz toxiques siamois, industriel contre victorien' },
  { id: 'ramoloss-ramolossgalar', champA: 'Ramoloss', champB: 'Ramoloss de Galar', theme: 'Même air ahuri, queue mordue par une crevette classique ou épicée' },
  { id: 'flagadoss-flagadossgalar', champA: 'Flagadoss', champB: 'Flagadoss de Galar', theme: 'Même carapace-pince, forme psychique contre forme mercenaire' },
  { id: 'roigada-roigadagalar', champA: 'Roigada', champB: 'Roigada de Galar', theme: 'Même couronne coquillage, royauté psychique contre royauté empoisonnée' },
  { id: 'canarticho-canartichogalar', champA: 'Canarticho', champB: 'Canarticho de Galar', theme: "Même canard au poireau, l'arme devient une épée dans la version galaroise" },
  { id: 'corayon-corayongalar', champA: 'Corayon', champB: 'Corayon de Galar', theme: 'Même corail vivant, rose vif contre blanc fossilisé' },
  { id: 'zigzaton-zigzatongalar', champA: 'Zigzaton', champB: 'Zigzaton de Galar', theme: 'Même raton en zigzag, rayures marron contre rayures noir et blanc' },
  { id: 'lineon-lineongalar', champA: 'Linéon', champB: 'Linéon de Galar', theme: 'Même mustélidé véloce, forme classique contre forme kleptomane' },
  { id: 'darumarond-darumarondgalar', champA: 'Darumarond', champB: 'Darumarond de Galar', theme: 'Même poupée culbuto, feu contre glace' },
  { id: 'darumacho-darumachogalar', champA: 'Darumacho', champB: 'Darumacho de Galar', theme: 'Même moine bourru, poings de feu contre poings glacés' },
  { id: 'limonde-limondegalar', champA: 'Limonde', champB: 'Limonde de Galar', theme: 'Même poisson-piège immobile, boue classique contre terrain enneigé' },
  { id: 'tutafeh-tutafehgalar', champA: 'Tutafeh', champB: 'Tutafeh de Galar', theme: 'Même masque errant, forme couchée contre forme empilée' },
  { id: 'mrmime-mrmimegalar', champA: 'M. Mime', champB: 'M. Mime de Galar', theme: 'Même mime silencieux, murs invisibles contre patinage sur glace' },
  { id: 'artikodin-artikodingalar', champA: 'Artikodin', champB: 'Artikodin de Galar', theme: 'Même oiseau légendaire de glace, plumage bleu contre psychique violet' },
  { id: 'electhor-electhorgalar', champA: 'Electhor', champB: 'Electhor de Galar', theme: 'Même oiseau légendaire électrique, ailes rapides contre combattant coureur' },
  { id: 'sulfura-sulfuragalar', champA: 'Sulfura', champB: 'Sulfura de Galar', theme: 'Même oiseau légendaire de feu, plumage rouge contre ténébreux sinistre' },
  { id: 'caninos-caninoshisui', champA: 'Caninos', champB: 'Caninos de Hisui', theme: 'Même chiot de feu loyal, crinière orange contre crinière blanche' },
  { id: 'voltorbe-voltorbehisui', champA: 'Voltorbe', champB: 'Voltorbe de Hisui', theme: 'Même Poké Ball vivante, électrique contre poison' },
  { id: 'zorua-zoruahisui', champA: 'Zorua', champB: 'Zorua de Hisui', theme: 'Même renard illusionniste, brun ténébreux contre blanc normal/glace' },
  { id: 'zoroark-zoroarkhisui', champA: 'Zoroark', champB: 'Zoroark de Hisui', theme: 'Même illusionniste rusé, crinière rouge contre crinière blanche' },
  { id: 'typhlosion-typhlosionhisui', champA: 'Typhlosion', champB: 'Typhlosion de Hisui', theme: 'Même volcan sur pattes, flammes physiques contre flammes spectrales' },
  { id: 'clamiral-clamiralhisui', champA: 'Clamiral', champB: 'Clamiral de Hisui', theme: 'Même samouraï loutre, armure classique contre armure spectrale' },
  { id: 'arcanin-arcaninhisui', champA: 'Arcanin', champB: 'Arcanin de Hisui', theme: 'Même légende canine majestueuse, crinière feu contre crinière roche/feu' },
  // --- Paires très difficiles : duos et trios jumeaux (undercover très dur à repérer) ---
  { id: 'nidoranm-nidoranf', champA: 'Nidoran♂', champB: 'Nidoran♀', theme: "Même Pokémon poison, seule l'oreille et la couleur diffèrent" },
  { id: 'posipi-negapi', champA: 'Posipi', champB: 'Négapi', theme: 'Souris électriques jumelles, symbole plus contre symbole moins' },
  { id: 'rondoudou-toudoudou', champA: 'Rondoudou', champB: 'Toudoudou', theme: "Même boule rose chanteuse, avant et après l'évolution" },
  { id: 'artikodin-electhor', champA: 'Artikodin', champB: 'Electhor', theme: 'Deux tiers du même trio légendaire, silhouette identique' },
  { id: 'electhor-sulfura', champA: 'Electhor', champB: 'Sulfura', theme: 'Deux tiers du même trio légendaire, silhouette identique' },
  { id: 'raikou-entei', champA: 'Raikou', champB: 'Entei', theme: 'Deux bêtes légendaires nées du même incendie, même silhouette féline' },
  { id: 'entei-suicune', champA: 'Entei', champB: 'Suicune', theme: 'Deux bêtes légendaires nées du même incendie, même silhouette féline' },
  { id: 'regirock-regice', champA: 'Regirock', champB: 'Regice', theme: 'Golems légendaires du même trio, roche contre glace' },
  { id: 'regice-registeel', champA: 'Regice', champB: 'Registeel', theme: 'Golems légendaires du même trio, glace contre acier' },
  { id: 'tokorico-tokopiyon', champA: 'Tokorico', champB: 'Tokopiyon', theme: 'Deux divinités tutélaires de la même île, même silhouette totémique' },
  { id: 'tokotoro-tokolosse', champA: 'Tokotoro', champB: 'Tokolosse', theme: 'Deux divinités tutélaires de la même île, même silhouette totémique' },
  { id: 'fulguris-boreas', champA: 'Fulguris', champB: 'Boréas', theme: 'Génies des forces de la nature, même silhouette humanoïde' },
  { id: 'demeteros-fulguris', champA: 'Démétéros', champB: 'Fulguris', theme: 'Génies des forces de la nature, même silhouette humanoïde' },
  { id: 'dialga-palkia', champA: 'Dialga', champB: 'Palkia', theme: 'Duo de la création, maîtres du temps et de l\'espace' },
  { id: 'reshiram-zekrom', champA: 'Reshiram', champB: 'Zekrom', theme: 'Dragons jumeaux légendaires, vérité blanche contre idéal noir' },
  { id: 'latias-latios', champA: 'Latias', champB: 'Latios', theme: 'Frère et sœur dragons légendaires, même silhouette aérienne' },
  { id: 'feunard-feunardalola', champA: 'Feunard', champB: "Feunard d'Alola", theme: 'Même renard à neuf queues, feu contre glace' },
  { id: 'persian-persianalola', champA: 'Persian', champB: "Persian d'Alola", theme: 'Même félin à pièce d\'or, pelage crème contre pelage violet' },
  { id: 'triopikeur-triopikeuralola', champA: 'Triopikeur', champB: "Triopikeur d'Alola", theme: 'Même trio de taupes souterraines, marron contre moustaches dorées' },
  { id: 'gravalanch-gravalanchalola', champA: 'Gravalanch', champB: "Gravalanch d'Alola", theme: 'Même roche à deux bras, magnétisme et fragments de métal' },
  { id: 'grolem-grolemalola', champA: 'Grolem', champB: "Grolem d'Alola", theme: 'Même golem de pierre, lanceur de rochers contre canon magnétique' },
  { id: 'grotadmorv-grotadmorvalola', champA: 'Grotadmorv', champB: "Grotadmorv d'Alola", theme: 'Même montagne de boue toxique, violet contre déchets recyclés' },
  { id: 'rattatac-rattatacalola', champA: 'Rattatac', champB: "Rattatac d'Alola", theme: 'Même rongeur évolué, marron des villes contre pelage sombre nocturne' },
  { id: 'rattata-rattataalola', champA: 'Rattata', champB: "Rattata d'Alola", theme: 'Même petit rongeur, marron des villes contre pelage sombre nocturne' },
  { id: 'electrode-electrodehisui', champA: 'Électrode', champB: 'Électrode de Hisui', theme: 'Même Poké Ball explosive, électrique contre poison' },
  { id: 'muplodocus-muplodocushisui', champA: 'Muplodocus', champB: 'Muplodocus de Hisui', theme: 'Même limace dragon géante, forme classique contre forme spectrale' },
  { id: 'archeduc-archeduchisui', champA: 'Archéduc', champB: 'Archéduc de Hisui', theme: 'Même archer hibou, plante contre spectre' },
  { id: 'raikou-suicune', champA: 'Raikou', champB: 'Suicune', theme: 'Deux bêtes légendaires nées du même incendie, même silhouette féline' },
  { id: 'regirock-registeel', champA: 'Regirock', champB: 'Registeel', theme: 'Golems légendaires du même trio, roche contre acier' },
  { id: 'zekrom-kyurem', champA: 'Zekrom', champB: 'Kyurem', theme: 'Dragons légendaires d\'Unys, même silhouette biomécanique' },
  { id: 'reshiram-kyurem', champA: 'Reshiram', champB: 'Kyurem', theme: 'Dragons légendaires d\'Unys, même silhouette biomécanique' },
  { id: 'boreas-demeteros', champA: 'Boréas', champB: 'Démétéros', theme: 'Génies des forces de la nature, même silhouette humanoïde' },
  { id: 'solgaleo-necrozma', champA: 'Solgaleo', champB: 'Necrozma', theme: 'Lion cuirassé de lumière et le prisme qui dévore la lumière' },
  { id: 'lunala-necrozma', champA: 'Lunala', champB: 'Necrozma', theme: 'Chauve-souris spectrale de lumière et le prisme qui la dévore' },
  { id: 'doduo-dodrio', champA: 'Doduo', champB: 'Dodrio', theme: 'Même oiseau coureur, deux têtes contre trois têtes' },
  { id: 'tokorico-tokotoro', champA: 'Tokorico', champB: 'Tokotoro', theme: 'Deux divinités tutélaires, même silhouette totémique' },
  { id: 'tokopiyon-tokolosse', champA: 'Tokopiyon', champB: 'Tokolosse', theme: 'Deux divinités tutélaires, même silhouette totémique' },
  { id: 'artikodin-sulfura', champA: 'Artikodin', champB: 'Sulfura', theme: 'Deux tiers du même trio légendaire, silhouette identique' },
  { id: 'mimiqui-zoroark', champA: 'Mimiqui', champB: 'Zoroark', theme: 'Pokémon célèbres pour leurs déguisements et illusions' },
  { id: 'metamorph-mimiqui', champA: 'Métamorph', champB: 'Mimiqui', theme: "Pokémon qui empruntent l'apparence d'un autre" },
  { id: 'artikodingalar-electhorgalar', champA: 'Artikodin de Galar', champB: 'Electhor de Galar', theme: 'Deux tiers du même trio légendaire galarois, silhouette identique' },

  // --- Paires moyennes (thématiquement proches, undercover repérable avec attention) ---
  { id: 'bulbizarre-tortipouss', champA: 'Bulbizarre', champB: 'Tortipouss', theme: 'Starters plante de première évolution, générations différentes' },
  { id: 'florizarre-torterra', champA: 'Florizarre', champB: 'Torterra', theme: 'Starters plante à leur forme finale' },
  { id: 'carapuce-moustillon', champA: 'Carapuce', champB: 'Moustillon', theme: 'Starters eau de première évolution, générations différentes' },
  { id: 'tortank-laggron', champA: 'Tortank', champB: 'Laggron', theme: 'Starters eau à leur forme finale, carapace massive' },
  { id: 'salameche-poussifeu', champA: 'Salamèche', champB: 'Poussifeu', theme: 'Starters feu de première évolution, générations différentes' },
  { id: 'dracaufeu-bresegali', champA: 'Dracaufeu', champB: 'Braségali', theme: 'Starters feu à leur forme finale, silhouette combattante' },
  { id: 'hericendre-gruikui', champA: 'Héricendre', champB: 'Gruikui', theme: 'Starters feu de première évolution, générations différentes' },
  { id: 'typhlosion-roitiflam', champA: 'Typhlosion', champB: 'Roitiflam', theme: 'Starters feu à leur forme finale, posture bipède imposante' },
  { id: 'simiabraz-torgamord', champA: 'Simiabraz', champB: 'Torgamord', theme: 'Starters feu à leur forme finale, silhouette féline/simiesque' },
  { id: 'pyrobut-bresegali', champA: 'Pyrobut', champB: 'Braségali', theme: 'Starters feu à leur forme finale, combattants sur deux pattes' },
  { id: 'tiplouf-kaiminus', champA: 'Tiplouf', champB: 'Kaiminus', theme: 'Starters eau de première évolution, générations différentes' },
  { id: 'pingoleon-aligatueur', champA: 'Pingoléon', champB: 'Aligatueur', theme: 'Starters eau à leur forme finale, prédateur bipède' },
  { id: 'amphinobi-laggron', champA: 'Amphinobi', champB: 'Laggron', theme: 'Starters eau à leur forme finale, physique athlétique' },
  { id: 'mewtwo-mew', champA: 'Mewtwo', champB: 'Mew', theme: "Duo génétique, l'original et son clone créé en laboratoire" },
  { id: 'dracolosse-carchacrok', champA: 'Dracolosse', champB: 'Carchacrok', theme: 'Pseudo-légendaires dragons, silhouette massive ailée' },
  { id: 'carchacrok-drattak', champA: 'Carchacrok', champB: 'Drattak', theme: 'Pseudo-légendaires dragons, mâchoire et ailes imposantes' },
  { id: 'metalosse-tyranocif', champA: 'Métalosse', champB: 'Tyranocif', theme: 'Pseudo-légendaires emblématiques, carapace/écailles blindées' },
  { id: 'hooh-lugia', champA: 'Ho-Oh', champB: 'Lugia', theme: 'Oiseaux légendaires emblématiques de génération, gardiens des cieux/mers' },
  { id: 'groudon-kyogre', champA: 'Groudon', champB: 'Kyogre', theme: 'Duo légendaire climatique, continent contre océan' },
  { id: 'dialga-giratina', champA: 'Dialga', champB: 'Giratina', theme: 'Trio de la création, temps contre antimatière' },
  { id: 'xerneas-yveltal', champA: 'Xerneas', champB: 'Yveltal', theme: 'Duo légendaire vie et mort, cerf de lumière contre oiseau ténébreux' },
  { id: 'solgaleo-lunala', champA: 'Solgaleo', champB: 'Lunala', theme: 'Duo légendaire soleil et lune, lion blindé contre chauve-souris spectrale' },
  { id: 'zacian-zamazenta', champA: 'Zacian', champB: 'Zamazenta', theme: 'Loups légendaires guerriers, épée royale contre bouclier royal' },
  { id: 'koraidon-miraidon', champA: 'Koraidon', champB: 'Miraidon', theme: 'Montures légendaires du passé et du futur' },
  { id: 'lucario-zeraora', champA: 'Lucario', champB: 'Zeraora', theme: "Combattants fan-favoris à l'aura, bipèdes agiles et populaires" },
  { id: 'noctali-mentali', champA: 'Noctali', champB: 'Mentali', theme: 'Évolutions jumelles d\'Évoli, ténèbres contre psychique' },
  { id: 'pyroli-aquali', champA: 'Pyroli', champB: 'Aquali', theme: "Évolutions jumelles d'Évoli, feu contre eau" },
  { id: 'givrali-phyllali', champA: 'Givrali', champB: 'Phyllali', theme: "Évolutions jumelles d'Évoli, glace contre plante" },
  { id: 'absol-zoroark', champA: 'Absol', champB: 'Zoroark', theme: 'Canidés mystérieux et ténébreux au pelage frappant' },
  { id: 'ectoplasma-mimiqui', champA: 'Ectoplasma', champB: 'Mimiqui', theme: 'Fantômes farceurs emblématiques, sourire menaçant' },
  { id: 'voltali-pyroli', champA: 'Voltali', champB: 'Pyroli', theme: "Évolutions jumelles d'Évoli, électrique contre feu" },
  { id: 'nymphali-givrali', champA: 'Nymphali', champB: 'Givrali', theme: "Évolutions jumelles d'Évoli, fée contre glace" },
  { id: 'zygarde-xerneas', champA: 'Zygarde', champB: 'Xerneas', theme: "Gardiens légendaires de Kalos, garants de l'équilibre et de la vie" },
  { id: 'zygarde-yveltal', champA: 'Zygarde', champB: 'Yveltal', theme: "Gardiens légendaires de Kalos, garants de l'équilibre et de la mort" },
  { id: 'rayquaza-zygarde', champA: 'Rayquaza', champB: 'Zygarde', theme: 'Serpents-dragons légendaires garants de l\'équilibre écologique' },
  { id: 'mewtwo-deoxys', champA: 'Mewtwo', champB: 'Deoxys', theme: "Légendaires nés d'une manipulation génétique ou spatiale" },
  { id: 'lucario-riolu', champA: 'Lucario', champB: 'Riolu', theme: "Évolution père-fils au combat guidé par l'aura" },
  { id: 'leviator-dracolosse', champA: 'Léviator', champB: 'Dracolosse', theme: 'Serpents-dragons emblématiques, écailles bleues imposantes' },
  { id: 'sulfura-dracaufeu', champA: 'Sulfura', champB: 'Dracaufeu', theme: 'Silhouettes ailées de feu emblématiques' },
  { id: 'aquali-leviator', champA: 'Aquali', champB: 'Léviator', theme: 'Pokémon eau emblématiques, tailles radicalement opposées' },
  { id: 'arceus-mewtwo', champA: 'Arceus', champB: 'Mewtwo', theme: 'Légendaires ultra-puissants, créateur originel contre création de laboratoire' },
  { id: 'salameche-reptincel', champA: 'Salamèche', champB: 'Reptincel', theme: 'Même lézard de feu, petite salamandre contre grand reptile bipède' },

  // --- Paires faciles (undercover plus repérable, silhouettes très différentes) ---
  { id: 'pikachu-magicarpe', champA: 'Pikachu', champB: 'Magicarpe', theme: 'Mascotte électrique populaire contre poisson tristement célèbre pour sa faiblesse' },
  { id: 'mewtwo-ronflex', champA: 'Mewtwo', champB: 'Ronflex', theme: 'Puissance psychique redoutable contre géant paresseux qui bloque les routes' },
  { id: 'magicarpe-leviator', champA: 'Magicarpe', champB: 'Léviator', theme: "La même espèce avant et après une évolution radicale, poisson contre dragon marin" },
  { id: 'dracaufeu-papilusion', champA: 'Dracaufeu', champB: 'Papilusion', theme: 'Deux Pokémon volants emblématiques de génération 1, dragon contre papillon' },
  { id: 'ronflex-wailord', champA: 'Ronflex', champB: 'Wailord', theme: 'Deux géants immobiles, montagne endormie contre baleine gigantesque' },
  { id: 'rondoudou-qulbutoke', champA: 'Rondoudou', champB: 'Qulbutoké', theme: 'Deux boules roses absurdes et attachantes' },
  { id: 'metamorph-mew', champA: 'Métamorph', champB: 'Mew', theme: 'Le mystérieux imitateur contre le mythique ancêtre de tous les Pokémon' },
  { id: 'magneti-voltorbe', champA: 'Magnéti', champB: 'Voltorbe', theme: 'Deux Pokémon ronds électriques de génération 1, aimant contre Poké Ball piégée' },
  { id: 'ectoplasma-alakazam', champA: 'Ectoplasma', champB: 'Alakazam', theme: 'Icônes psychique et spectre de génération 1, silhouettes opposées' },
  { id: 'bresegali-pingoleon', champA: 'Braségali', champB: 'Pingoléon', theme: 'Starters finaux de générations différentes, silhouettes radicalement opposées' },
  { id: 'rayquaza-groudon', champA: 'Rayquaza', champB: 'Groudon', theme: 'Trio météorologique légendaire, serpent des cieux contre titan tellurique' },
  { id: 'arceus-giratina', champA: 'Arceus', champB: 'Giratina', theme: 'Divinité créatrice contre gardien de la dimension distordue' },
  { id: 'ramoloss-psykokwak', champA: 'Ramoloss', champB: 'Psykokwak', theme: 'Deux Pokémon célèbres pour leur air complètement ahuri' },
  { id: 'evoli-metamorph', champA: 'Évoli', champB: 'Métamorph', theme: 'Le renard aux évolutions multiples contre le blob capable de tout imiter' },
  { id: 'lucario-carchacrok', champA: 'Lucario', champB: 'Carchacrok', theme: 'Fan-favoris emblématiques, silhouette bipède contre silhouette de requin dragon' },
  { id: 'pikachu-ronflex', champA: 'Pikachu', champB: 'Ronflex', theme: 'Mascotte électrique agile contre géant lent et somnolent' },
  { id: 'mewtwo-magicarpe', champA: 'Mewtwo', champB: 'Magicarpe', theme: 'Extrêmes de puissance, légende psychique contre poisson risible' },
  { id: 'rayquaza-magicarpe', champA: 'Rayquaza', champB: 'Magicarpe', theme: 'Dragon céleste légendaire contre poisson tristement célèbre pour sa faiblesse' },
  { id: 'dracaufeu-ronflex', champA: 'Dracaufeu', champB: 'Ronflex', theme: 'Dragon ailé fougueux contre géant immobile qui bloque les routes' },
  { id: 'evoli-ronflex', champA: 'Évoli', champB: 'Ronflex', theme: 'Petit renard agile aux évolutions multiples contre géant somnolent' },
  { id: 'arceus-magicarpe', champA: 'Arceus', champB: 'Magicarpe', theme: 'Divinité créatrice de tout l\'univers contre poisson tristement célèbre pour sa faiblesse' },
];
